DROP TABLE IF EXISTS COIN;
CREATE TABLE COIN ( 
COIN_ID INT AUTO_INCREMENT  PRIMARY KEY, 
COIN_CODE VARCHAR(255 CHAR), 
COIN_DESCRIPTION VARCHAR(255 CHAR), 
COIN_NAME VARCHAR(255 CHAR), 
COIN_RATE NUMBER, 
COIN_UPDATE_TIME TIMESTAMP );
